# 🧮 Day 4 — NumPy Foundations for AI & Machine Learning
### Python for AI Bootcamp · Self-Study Colab Notebook

**Who this is for:** B.Tech 4th-year students preparing for AI, Machine Learning, Deep Learning, and Generative AI. Beginner to intermediate.

**How to use this notebook**
- Run every code cell (`Shift + Enter`) and read the **Expected Output** below it.
- Try each **Practice Exercise** *before* opening the **Solution** beside it.
- If you miss the lecture, this notebook alone will teach you the topic.

> 🔗 **The chain we keep returning to:** `Python → NumPy → Pandas → Machine Learning → Deep Learning → Generative AI`. NumPy is link two — everything above stands on it.

---

## 1. Introduction to NumPy

**NumPy** (Numerical Python) is the library that lets Python do fast math on large grids of numbers. Those grids are called **arrays**.

Why should an AI student care? Because *every* dataset, image, and model weight in AI is ultimately an array of numbers. Master arrays and you are speaking the native language of machine learning.

**What NumPy gives you over plain Python:**
- Speed — calculations run in fast compiled C, often 10–100× faster than list loops.
- Clean code — do math on a whole dataset in one line, no manual loops.
- A bridge — Pandas, scikit-learn, TensorFlow, and PyTorch are all built on NumPy-style arrays.

## 2. Installing and Importing NumPy

Google Colab already has NumPy installed. On your own machine you would run `pip install numpy` once. Everywhere, we import it with the standard nickname `np`.

In [ ]:
# Colab already has NumPy. To install elsewhere, uncomment the next line:
# !pip install numpy

import numpy as np
print("NumPy version:", np.__version__)

**Expected Output** *(version may differ — that is fine):*
```
NumPy version: 1.26.4
```
✅ If this runs without an error, you are ready. From now on, `np` means NumPy.

## 3. Arrays — the core idea

An **array** is a grid of values, all of the same type, where each value has a position (an index starting at 0).

Compare a Python list with a NumPy array doing the same job: *add 5 to every number*.

In [ ]:
# Python list — needs a loop
marks_list = [80, 92, 75]
result = []
for m in marks_list:
    result.append(m + 5)
print("List way :", result)

# NumPy array — no loop, just math
marks = np.array([80, 92, 75])
print("NumPy way:", marks + 5)

**Expected Output**
```
List way : [85, 97, 80]
NumPy way: [85 97 80]
```
Notice the array printed **without commas** — that is how you can tell an array from a list at a glance. And `marks + 5` applied to *every* element automatically. That auto-applying behaviour is called **vectorization**, and it is everywhere in AI.

> ⚠️ **Common doubt:** With *lists*, `+` joins them together. With *arrays*, `+` adds them. Same symbol, different worlds.

### 🔧 Practice 3 — Try it yourself
Create an array `temps` holding `[30, 32, 35, 28]` and print every temperature **doubled**.

In [ ]:
# Your code here


<details><summary>💡 Solution 3</summary>

```python
temps = np.array([30, 32, 35, 28])
print(temps * 2)     # [60 64 70 56]
```
`temps * 2` multiplies every element by 2 — one clean expression, no loop.
</details>

## 4. Creating Arrays

Two ways to build arrays: **from data you already have**, and **from scratch** using factory functions.

In [ ]:
# From existing data
a = np.array([10, 20, 30])
b = np.array([[1, 2], [3, 4]])     # 2D from a list of lists

# From scratch
zeros  = np.zeros((2, 3))           # all zeros, shape 2x3
ones   = np.ones((2, 3))            # all ones
seq    = np.arange(0, 10, 2)        # start, stop(excluded), step
points = np.linspace(0, 1, 5)       # 5 evenly spaced values 0..1

print("a      :", a)
print("zeros  :\n", zeros)
print("seq    :", seq)
print("points :", points)

**Expected Output**
```
a      : [10 20 30]
zeros  :
 [[0. 0. 0.]
 [0. 0. 0.]]
seq    : [0 2 4 6 8]
points : [0.   0.25 0.5  0.75 1.  ]
```
🔑 **Two traps to remember:** `arange` **excludes** the stop value (no 10), while `linspace` **includes** both ends. `arange` takes a *step*; `linspace` takes a *count*.

### 🔧 Practice 4
1. Make a `3×3` array of all ones.
2. Make an array of even numbers from 0 to 20 using `arange`.

In [ ]:
# Your code here


<details><summary>💡 Solution 4</summary>

```python
print(np.ones((3, 3)))
print(np.arange(0, 21, 2))   # 0 2 4 ... 20  (stop is 21 so 20 is included)
```
Note we used `21` as the stop so that `20` is included, because `arange` excludes the stop value.
</details>

## 5. 1D Arrays — a single row (vectors)

A **1D array** is a straight line of values. In AI, one 1D array often describes **one example** — e.g. one student, one house, one customer. ML calls this a *feature vector*.

In [ ]:
student = np.array([78, 85, 90, 67, 88])   # one student's 5 subject marks

print("The array      :", student)
print("Shape          :", student.shape)   # (5,)  -> 5 values in 1 dimension
print("Number of dims :", student.ndim)    # 1
print("Data type      :", student.dtype)   # int64 (int32 on some Windows)
print("First mark     :", student[0])
print("Last mark      :", student[-1])

**Expected Output**
```
The array      : [78 85 90 67 88]
Shape          : (5,)
Number of dims : 1
Data type      : int64
First mark     : 78
Last mark      : 88
```
The shape `(5,)` is a one-item tuple — that trailing comma is normal Python and just means "5 values along one axis." 

### 🔧 Practice 5
Create a 1D array of any 6 ages and print its **shape** and its **middle two** values (positions 2 and 3).

In [ ]:
# Your code here


<details><summary>💡 Solution 5</summary>

```python
ages = np.array([21, 20, 22, 19, 23, 20])
print(ages.shape)     # (6,)
print(ages[2:4])      # positions 2 and 3 -> [22 19]
```
`ages[2:4]` slices positions 2 and 3 (stop index 4 is excluded).
</details>

## 6. 2D Arrays — rows and columns (matrices)

A **2D array** is a table: **rows = examples, columns = features**. This is exactly how a dataset looks before it goes into a model.

In [ ]:
# 4 students, 3 subjects each  -> shape (4, 3)
marks = np.array([
    [78, 85, 90],
    [67, 72, 80],
    [88, 91, 95],
    [55, 60, 70],
])

print("Shape        :", marks.shape)   # (4, 3) = 4 rows, 3 cols
print("Dimensions   :", marks.ndim)    # 2
print("Total values :", marks.size)    # 12
print("Row 0 (1st student) :", marks[0])
print("Value at row1,col2  :", marks[1, 2])

**Expected Output**
```
Shape        : (4, 3)
Dimensions   : 2
Total values : 12
Row 0 (1st student) : [78 85 90]
Value at row1,col2  : 80
```
Read shape `(4, 3)` as "four by three." Row-then-column ordering (`marks[1, 2]` = row 1, column 2) is the rule for everything in 2D.

### 🔧 Practice 6
From the `marks` array above, print **the third student's row** and **the value at row 3, column 0**.

In [ ]:
# Your code here


<details><summary>💡 Solution 6</summary>

```python
print(marks[2])      # third student -> [88 91 95]
print(marks[3, 0])   # row 3, col 0 -> 55
```
Remember counting starts at 0, so the *third* student is index `2`.
</details>

## 7. Indexing — grabbing single values

Indexing means "give me the value at position N." Positions start at **0**. Negative indices count from the **end** (`-1` is always the last).

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print("a[0]  =", a[0])    # first
print("a[2]  =", a[2])
print("a[-1] =", a[-1])   # last
print("a[-2] =", a[-2])   # second from end

m = np.array([[1, 2, 3], [4, 5, 6]])
print("m[0, 1] =", m[0, 1])   # row 0, col 1

**Expected Output**
```
a[0]  = 10
a[2]  = 30
a[-1] = 50
a[-2] = 40
m[0, 1] = 2
```
🧠 **Mental model:** positive index counts from the start of the street; negative counts back from the end.

### 🔧 Practice 7
For `a = np.array([5, 10, 15, 20, 25])`, print the **second** value and the **last** value using indexing.

In [ ]:
# Your code here


<details><summary>💡 Solution 7</summary>

```python
a = np.array([5, 10, 15, 20, 25])
print(a[1])    # second -> 10
print(a[-1])   # last   -> 25
```
</details>

## 8. Slicing — grabbing a range

Slicing uses `start : stop : step`. The golden rule: **start is included, stop is excluded.**

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60])
print("a[1:4]  =", a[1:4])    # indices 1,2,3
print("a[:3]   =", a[:3])     # from start
print("a[3:]   =", a[3:])     # to the end
print("a[::2]  =", a[::2])    # every 2nd

# 2D slicing: rows then columns
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("first column m[:, 0] =", m[:, 0])
print("first two rows m[0:2] =\n", m[0:2])

**Expected Output**
```
a[1:4]  = [20 30 40]
a[:3]   = [10 20 30]
a[3:]   = [40 50 60]
a[::2]  = [10 30 50]
first column m[:, 0] = [1 4 7]
first two rows m[0:2] =
 [[1 2 3]
 [4 5 6]]
```
🔑 `m[:, 0]` means "all rows, column 0" — that is how you pull a single feature column from a dataset.

> ⚠️ **Common doubt:** `a[1:4]` gives 3 values (1, 2, 3) — **not** four. The stop index 4 is excluded.

### 🔧 Practice 8
From `a = np.array([0, 1, 2, 3, 4, 5, 6, 7])`, slice out `[2, 3, 4]` and also every **third** element.

In [ ]:
# Your code here


<details><summary>💡 Solution 8</summary>

```python
a = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(a[2:5])    # [2 3 4]  (stop 5 excluded)
print(a[::3])    # [0 3 6]  every third
```
</details>

## 9. Reshaping — same data, new shape

`reshape` rearranges the same numbers into a different grid. **Rule:** the total number of elements must stay the same.

In [ ]:
a = np.arange(6)            # [0 1 2 3 4 5]
print("Original:", a, "shape", a.shape)

b = a.reshape(2, 3)
print("Reshaped 2x3:\n", b)

flat = b.flatten()          # squash back to 1D
print("Flattened:", flat)

auto = a.reshape(3, -1)     # -1 = 'you figure out this dimension'
print("reshape(3,-1):\n", auto)

**Expected Output**
```
Original: [0 1 2 3 4 5] shape (6,)
Reshaped 2x3:
 [[0 1 2]
 [3 4 5]]
Flattened: [0 1 2 3 4 5]
reshape(3,-1):
 [[0 1]
 [2 3]
 [4 5]]
```
The `-1` trick is a lifesaver: NumPy computes the missing dimension for you (here it works out to 2).

> ⚠️ **Common bug:** `a.reshape(4, 2)` on 6 elements fails — `4 × 2 = 8 ≠ 6`. The product of the new shape must equal the element count.

🔗 **AI connection:** a 28×28 image is reshaped to a 1D vector of 784 numbers before entering a basic neural network.

### 🔧 Practice 9
Take `np.arange(12)` and reshape it into a `3×4` grid, then flatten it back to 1D.

In [ ]:
# Your code here


<details><summary>💡 Solution 9</summary>

```python
x = np.arange(12)
grid = x.reshape(3, 4)
print(grid)
print(grid.flatten())   # back to [0 1 2 ... 11]
```
Try `x.reshape(5, 2)` too — it raises a `ValueError` because 5×2=10 ≠ 12.
</details>

## 10. Mathematical Operations

NumPy math is **element-wise** by default. Arrays combine slot-by-slot; a single number (scalar) is applied to every element.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a + b =", a + b)      # element-wise add
print("a * b =", a * b)      # element-wise multiply
print("b / a =", b / a)      # division -> floats

# Array vs scalar
prices = np.array([100, 250, 400])
print("with 18% GST:", prices * 1.18)

**Expected Output**
```
a + b = [11 22 33]
a * b = [10 40 90]
b / a = [10. 10. 10.]
with 18% GST: [118. 295. 472.]
```
🔗 **AI connection:** "multiply inputs by weights, then add a bias" — the core of a neural network layer — is just element-wise multiply and add on arrays.

> ⚠️ **Common doubt:** `a * b` is **element-wise**, not matrix multiplication. Matrix multiply is `a @ b` or `np.dot(a, b)` — a different operation.

### 🔧 Practice 10
Given `nums = np.array([4, 9, 16, 25])`, print each number's **square root** (hint: power of 0.5).

In [ ]:
# Your code here


<details><summary>💡 Solution 10</summary>

```python
nums = np.array([4, 9, 16, 25])
print(nums ** 0.5)   # [2. 3. 4. 5.]
```
Raising to the power `0.5` is the same as taking the square root.
</details>

## 11. Aggregations — many numbers into one

Aggregations summarise an array: `sum`, `mean`, `min`, `max`, `std`. For 2D arrays, the **axis** controls the direction.

In [ ]:
marks = np.array([72, 88, 95, 64, 79, 90, 58])
print("sum  :", marks.sum())
print("mean :", marks.mean())
print("max  :", marks.max())
print("min  :", marks.min())
print("std  :", round(float(marks.std()), 2))

# 2D: axis chooses direction
m = np.array([[1, 2, 3], [4, 5, 6]])
print("sum all      :", m.sum())
print("sum axis=0   :", m.sum(axis=0))   # down columns
print("sum axis=1   :", m.sum(axis=1))   # across rows

**Expected Output**
```
sum  : 546
mean : 78.0
max  : 95
min  : 58
std  : 12.91
sum all      : 21
sum axis=0   : [5 7 9]
sum axis=1   : [6 15]
```
🧭 **Axis trick:** think of `axis` as *the dimension that disappears*. `axis=0` collapses the rows → one number per **column**. `axis=1` collapses the columns → one number per **row**.

> ⚠️ **Common bug:** mixing up `axis=0` and `axis=1`. Getting the axis wrong is the #1 silent mistake in ML data code — picture the arrows before you type.

### 🔧 Practice 11
For `marks` above, count how many students scored **above the class average**.

In [ ]:
# Your code here


<details><summary>💡 Solution 11</summary>

```python
above = (marks > marks.mean()).sum()
print(above)   # 4
```
`marks > marks.mean()` makes a True/False array; summing it counts the Trues (True = 1). This trick — *boolean masking* — returns next week in Pandas filtering.
</details>

## 12. Broadcasting — stretching a small array to fit a big one

When shapes don't match, NumPy automatically **stretches** the smaller array so the math still works — without actually copying data. You have already used it: `a + 5` is broadcasting.

In [ ]:
a = np.array([1, 2, 3])
print("a + 10 =", a + 10)        # 10 stretched across all elements

# A 1D row added to every row of a 2D matrix
m = np.array([[1, 1, 1],
              [2, 2, 2]])
row = np.array([10, 20, 30])
print("m + row =\n", m + row)

**Expected Output**
```
a + 10 = [11 12 13]
m + row =
 [[11 21 31]
 [12 22 32]]
```
The row `[10, 20, 30]` was added to **every** row of `m`. 🔗 **AI connection:** this is exactly how a single bias vector is added to every example in a batch inside a neural network.

> ⚠️ **Rule of thumb:** line shapes up from the right; each pair must be **equal or one of them must be 1**. Otherwise NumPy raises a shape error.

### 🔧 Practice 12
Add the row `[100, 200]` to **both** rows of `np.array([[1, 2], [3, 4]])` using broadcasting.

In [ ]:
# Your code here


<details><summary>💡 Solution 12</summary>

```python
m = np.array([[1, 2], [3, 4]])
print(m + np.array([100, 200]))
# [[101 202]
#  [103 204]]
```
</details>

---
## ⚡ Mini Challenge

You are given daily step counts for one week. **Without writing a loop**, find the total steps, the average per day, and the single most active day's count.
```python
steps = np.array([5400, 8200, 7600, 3000, 9100, 12000, 6700])
```

In [ ]:
steps = np.array([5400, 8200, 7600, 3000, 9100, 12000, 6700])
# Your code here


<details><summary>💡 Mini Challenge Solution</summary>

```python
print("Total  :", steps.sum())          # 52000
print("Average:", steps.mean())         # 7428.57...
print("Best   :", steps.max())          # 12000
```
All three are single-call aggregations — no loops needed.
</details>

## 🏆 Challenge Problem — Normalise a dataset (real ML skill)

Machine-learning models train better when each feature is **standardised**: subtract the mean and divide by the standard deviation, so values are centred around 0.

Standardise this feature column **in one expression** using broadcasting:
```python
feature = np.array([50, 60, 70, 80, 90])
```
Then verify the new mean is ~0.

In [ ]:
feature = np.array([50, 60, 70, 80, 90])
# Your code here


<details><summary>💡 Challenge Solution</summary>

```python
standardised = (feature - feature.mean()) / feature.std()
print(standardised)            # [-1.41 -0.71  0.  0.71  1.41]
print(round(standardised.mean(), 6))   # 0.0  (centred!)
```
This exact line — `(x - x.mean()) / x.std()` — is run on real datasets before training almost every ML model. You just did professional feature scaling with broadcasting and aggregations combined.
</details>

---
## 📊 Real-World Dataset Examples

Below are three small but realistic ways arrays show up in AI work.

### A. Student Marks Dataset
Rows = students, columns = subjects. We compute each student's average and the class topper per subject.

In [ ]:
# rows: 4 students | cols: Math, Physics, CS
marks = np.array([
    [78, 85, 90],
    [67, 72, 80],
    [88, 91, 95],
    [55, 60, 70],
])

student_avg = marks.mean(axis=1)        # average per student (across subjects)
subject_top = marks.max(axis=0)         # top score per subject (down students)

print("Each student's average:", student_avg)
print("Topper mark per subject:", subject_top)
print("Class overall average :", round(marks.mean(), 2))

**Expected Output**
```
Each student's average: [84.33333333 73.         91.33333333 61.66666667]
Topper mark per subject: [88 91 95]
Class overall average : 77.58
```
`axis=1` summarised *per student*; `axis=0` summarised *per subject*. Choosing the axis correctly is the whole game.

### B. Sales Dataset
Rows = months, columns = products. We find total sales per product and the best-selling month.

In [ ]:
# rows: 3 months | cols: 4 products
sales = np.array([
    [120, 90, 60, 200],
    [150, 80, 70, 220],
    [100, 95, 65, 210],
])

per_product = sales.sum(axis=0)     # total each product across months
per_month   = sales.sum(axis=1)     # total each month across products

print("Total per product:", per_product)
print("Total per month  :", per_month)
print("Best month index :", per_month.argmax())   # which month sold most

**Expected Output**
```
Total per product: [370 265 195 630]
Total per month  : [470 520 470]
Best month index : 1
```
`argmax()` returns the **position** of the largest value — here month index 1 (the second month) was best. `argmax` is heavily used in AI to pick the most likely class from a model's output.

### C. Image as an Array
A grayscale image is just a 2D grid of brightness values (0 = black, 255 = white). Let's make a tiny 5×5 "image," then flatten it the way a neural network would.

In [ ]:
# a tiny 5x5 grayscale image (0=black ... 255=white)
image = np.array([
    [  0,  0, 255,  0,  0],
    [  0,255, 255,255,  0],
    [255,255, 255,255,255],
    [  0,255, 255,255,  0],
    [  0,  0, 255,  0,  0],
])

print("Image shape :", image.shape)     # (5, 5)
print("Brightest pixel value:", image.max())
print("Flattened length:", image.flatten().shape)   # (25,)

# normalise pixels to 0..1 (standard first step before feeding a model)
print("Normalised max:", (image / 255).max())

**Expected Output**
```
Image shape : (5, 5)
Brightest pixel value: 255
Flattened length: (25,)
Normalised max: 1.0
```
🔗 The 5×5 image becomes a length-25 vector after `flatten()`, and dividing by 255 scales pixels to 0–1 — the exact preprocessing real image models use on the MNIST digit dataset (where 28×28 images flatten to 784 numbers).

---
## 🔗 How This Connects to Machine Learning

Everything you practised today is a building block of real AI systems:

| What you learned today | Where it shows up in ML / AI |
|---|---|
| Creating arrays | Loading datasets into memory |
| 1D arrays | One example = one feature vector |
| 2D arrays | A full dataset = rows × features |
| Indexing & slicing | Splitting data into train/test, selecting feature columns |
| Reshaping & flatten | Turning images into model inputs |
| Element-wise math | `inputs × weights + bias` inside every neural layer |
| Aggregations (mean, std) | Summarising data & standardising features |
| Broadcasting | Adding a bias vector across a whole batch |

**The takeaway:** a machine-learning model is, underneath, a long sequence of array operations repeated millions of times. The data going in, the maths during training, and the predictions coming out are all arrays.

> 🚀 **Next: Day 5 — Pandas.** A Pandas *DataFrame* is basically a NumPy 2D array with **named** rows and columns, so you can write `df["marks"]` instead of `m[:, 2]`. Everything you learned here carries straight over.

**Great work — you now speak the native language of AI: arrays.** 🎉